name: CrazyGeo
main: de.st_ddt.crazygeo.CrazyGeo
author: ST-DDT
version: 0.3.2
website: http://dev.bukkit.org/server-mods/crazygeo/
# requires CrazyCore v10.4 or later
depend: [CrazyCore]
softdepend: [WorldEdit]
description: >
            CrazyGeo needed for all CrazyPlugins using region containers.
commands:
  crazygeo:
    description: Region selection
    usage: /<command> [Subcommands...]
    aliases: [geo]
permissions:
  crazygeo.*:
    description: Access to all commands (Subsection geo)
    default: op
    children:
      crazygeo.weimport: true