name: CrazyGeo
main: de.st_ddt.crazygeo.CrazyGeo
author: ST-DDT
#C*=needed core version
version: C7_0.1
softdepend: [WorldEdit,PermissionsBukkit]
depend: [CrazyCore]
description: >
            CrazyPlugin Core needed for all CrazyPlugins
commands:
  crazygeo:
    description: Region selection
    usage: /<command> [Subcommands...]
    aliases: [geo]
permissions:
  crazygeo.*:
    description: Access to all commands (Subsection geo)
    default: op
    children:
      crazygeo.weimport: true