name: CrazyGeo
main: de.st_ddt.crazygeo.CrazyGeo
author: ST-DDT
version: 0.2.3
# requires CrazyCore v8 or later
depend: [CrazyCore]
softdepend: [WorldEdit]
description: >
            CrazyGeo needed for all CrazyPlugins using region containers.
commands:
  crazygeo:
    description: Region selection
    usage: /<command> [Subcommands...]
    aliases: [geo]
permissions:
  crazygeo.*:
    description: Access to all commands (Subsection geo)
    default: op
    children:
      crazygeo.weimport: true